import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pt' | 'en';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Portuguese translations
const ptTranslations = {
  // Navigation
  'nav.explore': 'Explorar',
  'nav.add': 'Adicionar',
  'nav.about': 'Sobre',
  'nav.login': 'Entrar',
  'nav.logout': 'Sair',
  'nav.admin': 'Admin',
  'nav.profile': 'Perfil',
  'nav.photos': 'Fotos',

  // Auth
  'auth.login_title': 'Entrar',
  'auth.login_subtitle': 'Entre na sua conta para adicionar e gerir os seus lugares.',
  'auth.register_title': 'Criar Conta',
  'auth.register_subtitle': 'Crie uma conta para começar a partilhar os seus lugares secretos.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.display_name': 'Nome',
  'auth.password_hint': 'Mínimo de 8 caracteres',
  'auth.login_button': 'Entrar',
  'auth.register_button': 'Criar Conta',
  'auth.logging_in': 'A entrar...',
  'auth.creating_account': 'A criar conta...',
  'auth.no_account': 'Ainda não tem conta?',
  'auth.have_account': 'Já tem conta?',
  'auth.create_one': 'Criar uma',
  'auth.login_here': 'Entrar',
  'auth.posting_as': 'A publicar como',
  'auth.generic_error': 'Ocorreu um erro. Tente novamente.',
  'auth.passwords_dont_match': 'As passwords não coincidem.',

  // Auth - forgot/reset password
  'auth.forgot_password': 'Esqueceu-se da password?',
  'auth.forgot_title': 'Recuperar Password',
  'auth.forgot_subtitle': 'Indique o seu email e enviamos um link para redefinir a password.',
  'auth.forgot_button': 'Enviar link',
  'auth.forgot_sending': 'A enviar...',
  'auth.forgot_check_email_title': 'Verifique o seu email',
  'auth.forgot_check_email_desc': 'Se existir uma conta com este email, enviámos um link para redefinir a password.',
  'auth.forgot_dev_title': 'Password temporária gerada',
  'auth.forgot_dev_desc': 'Ainda não há um serviço de email configurado, por isso aqui está uma password temporária para entrar:',
  'auth.forgot_dev_copy': 'Copiar',
  'auth.forgot_dev_copied': 'Copiado!',
  'auth.forgot_dev_note': 'Isto só aparece porque o email ainda não está configurado (modo de desenvolvimento). Depois de entrar, recomendamos alterar a password.',
  'auth.back_to_login': 'Voltar a entrar',
  'auth.reset_title': 'Nova Password',
  'auth.reset_subtitle': 'Escolha uma nova password para a sua conta.',
  'auth.reset_new_password': 'Nova password',
  'auth.reset_confirm_password': 'Confirmar password',
  'auth.reset_button': 'Redefinir password',
  'auth.reset_saving': 'A guardar...',
  'auth.reset_invalid_title': 'Link inválido',
  'auth.reset_invalid_desc': 'Este link de redefinição está em falta ou é inválido. Peça um novo.',
  'auth.reset_success_title': 'Password redefinida',
  'auth.reset_success_desc': 'A sua password foi alterada com sucesso. Já pode entrar.',

  // Auth - email verification
  'auth.verify_checking': 'A confirmar o seu email...',
  'auth.verify_success_title': 'Email confirmado!',
  'auth.verify_success_desc': 'O seu email foi confirmado com sucesso.',
  'auth.verify_go_home': 'Ir para o início',
  'auth.verify_invalid_title': 'Não foi possível confirmar',
  'auth.verify_invalid_desc': 'Este link de confirmação está em falta, expirou ou já foi usado.',
  'auth.verify_banner_text': 'Confirme o seu email para garantir o acesso à sua conta.',
  'auth.verify_banner_resend': 'Reenviar email',
  'auth.verify_banner_sending': 'A enviar...',
  'auth.verify_banner_sent': 'Email de confirmação enviado — verifique a sua caixa de entrada.',

  // Common
  'common.loading': 'Carregando...',
  'common.submit': 'Enviar',
  'common.cancel': 'Cancelar',
  'common.save': 'Salvar',
  'common.delete': 'Excluir',
  'common.clear_all': 'Limpar tudo',
  'common.edit': 'Editar',
  'common.close': 'Fechar',
  'common.back': 'Voltar',
  'common.next': 'Próximo',
  'common.previous': 'Anterior',
  'common.search': 'Pesquisar',
  'common.filter': 'Filtrar',
  'common.sort': 'Ordenar',

  // Categories
  'category.restaurant': 'Restaurante/Café',
  'category.bar': 'Bar/Loja de Bebidas',
  'category.nature': 'Natureza',
  'category.art': 'Arte',
  'category.view': 'Vista',
  'category.peculiar': 'Peculiar',
  'category.all': 'Todos',

  // Form
  'form.title': 'Título',
  'form.description': 'Descrição',
  'form.category': 'Categoria',
  'form.tags': 'Tags',
  'form.location': 'Localização',
  'form.images': 'Imagens',
  'form.submit': 'Enviar Local',
  'form.submitting': 'Enviando...',
  'form.required': 'obrigatório',

  // Placeholders
  'placeholder.title': 'Nome do lugar',
  'placeholder.description': 'Descreva este lugar e o que o torna especial...',
  'placeholder.select_category': 'Selecione uma categoria',
  'placeholder.search_location': 'Pesquisar local...',

  // Messages
  'message.submit_success': 'Seu lugar foi enviado com sucesso e será revisado pela nossa equipe em breve.',
  'message.submit_success_approval': 'Após a aprovação, seu lugar aparecerá no mapa e poderá ser descoberto por outros usuários.',
  'message.submit_another': 'Adicionar Outro Lugar',
  'message.explore_more': 'Explorar Mais Lugares',
  'message.no_places': 'Nenhum lugar encontrado',
  'message.no_places_suggestion': 'Tente alterar os filtros ou seja o primeiro a adicionar um lugar!',
  'message.add_first_place': 'Adicionar Lugar',

  // Footer
  'footer.description': 'Descubra os lugares secretos de Maputo compartilhados por locais.',
  'footer.explore': 'Explorar',
  'footer.community': 'Comunidade',
  'footer.legal': 'Legal',
  'footer.copyright': '© {year} Hidden Gem. Todos os direitos reservados.',
  'footer.lists': 'Listas',
  'footer.categories': 'Categorias',
  'footer.guidelines': 'Diretrizes',
  'footer.contact': 'Contacto',
  'footer.privacy': 'Privacidade',
  'footer.terms': 'Termos',

  // Submit page
  'submit.title': 'Compartilhe um Lugar Secreto',
  'submit.subtitle': 'Ajude outros a descobrirem os lugares especiais de Maputo. Todos os lugares são revisados antes de serem publicados.',
  'submit.guidelines_title': 'Diretrizes da Comunidade',
  'submit.login_required_title': 'Entre para adicionar um lugar',
  'submit.login_required_desc': 'É preciso ter uma conta para partilhar os seus lugares secretos com a comunidade.',
  'submit.login_required_button': 'Entrar',
  'submit.login_required_register': 'Ainda não tem conta?',
  'submit.guideline_1': 'Compartilhe lugares que não sejam amplamente conhecidos ou turísticos',
  'submit.guideline_2': 'Forneça informações precisas e detalhadas sobre o local',
  'submit.guideline_3': 'Respeite a privacidade e a segurança dos locais compartilhados',
  'submit.guideline_4': 'Não compartilhe locais que possam causar danos ambientais ou perturbar comunidades locais',
  'submit.map_title': 'Localização no Mapa',

  // Maputo page
  'maputo.title': 'Maputo',
  'maputo.secret_places': 'lugares secretos',
  'maputo.loading_places': 'Carregando lugares...',
  'maputo.all': 'Todos',
  'maputo.popular': 'Popular',
  'maputo.newest': 'Mais Recentes',
  'maputo.top_rated': 'Melhor Avaliados',
  'maputo.closest': 'Mais Próximos',
  'maputo.view_grid': 'Grelha',
  'maputo.view_map': 'Mapa',

  // Hero
  'hero.title': 'Descubra os lugares secretos de Maputo compartilhados por locais.',
  'hero.subtitle': 'Encontre cafés escondidos, vistas locais, trilhas não sinalizadas e muito mais.',
  'hero.explore_button': 'Explorar Maputo.',
  'hero.share_button': 'Compartilhar um Local.',
  'hero.wander_button': 'Modo Wander',

  // Index page
  'index.featured_title': 'Lugares em Destaque',
  'index.featured_subtitle': 'Descubra alguns dos lugares mais especiais compartilhados pela nossa comunidade',
  'index.featured_empty': 'Ainda não há lugares aprovados. Seja o primeiro a partilhar um!',
  'index.view_all_maputo': 'Ver todos os lugares de Maputo',
  'index.categories_title': 'Explorar por Categoria',
  'index.categories_subtitle': 'Encontre lugares especiais organizados por tipo de experiência',
  'index.how_it_works_title': 'Como Funciona',
  'index.how_it_works_subtitle': 'Junte-se à nossa comunidade e comece a descobrir os lugares mais autênticos de Maputo',
  'index.discover_title': 'Descubra',
  'index.discover_desc': 'Explore lugares únicos no mapa ou navegue pelas categorias para encontrar algo especial',
  'index.share_title': 'Compartilhe',
  'index.share_desc': 'Adicione seus próprios lugares secretos e ajude outros a descobrirem a cidade',
  'index.vote_title': 'Vote',
  'index.vote_desc': 'Avalie os lugares para ajudar a comunidade a encontrar os melhores locais',
  'index.lists_title': 'Listas Populares',
  'index.lists_subtitle': 'Descubra coleções especiais de lugares selecionados por nossa comunidade',
  'index.cafes_list_title': 'Cafés Escondidos de Maputo',
  'index.cafes_list_desc': 'Os melhores cafés que só os locais conhecem',
  'index.views_list_title': 'Vistas Incríveis de Maputo',
  'index.views_list_desc': 'Os melhores mirantes e pontos de vista da cidade',
  'index.view_all_lists': 'Ver todas as listas',
  'index.recent_photos_title': 'Fotos de Quem Já Foi',
  'index.recent_photos_subtitle': 'Momentos partilhados por pessoas que visitaram estes lugares',
  'index.view_all_photos': 'Ver todas as fotos',
  'index.newsletter_title': 'Receba Novos Lugares',
  'index.newsletter_subtitle': 'Inscreva-se na nossa newsletter para receber os lugares mais recentes adicionados à nossa comunidade',
  'index.subscribe_button': 'Inscrever-se',

  // Categories page
  'categories.title': 'Explorar por Categorias',
  'categories.subtitle': 'Encontre lugares especiais organizados por tipo de experiência',

  // About page
  'about.how_it_works_title': 'Como Funciona',
  'about.discover_title': 'Descubra',
  'about.discover_desc': 'Explore nosso mapa interativo e encontre lugares únicos em Maputo, de cafés escondidos a trilhas incríveis.',
  'about.share_title': 'Compartilhe',
  'about.share_desc': 'Adicione seus próprios lugares favoritos e ajude outros a descobrirem a cidade como um local.',
  'about.vote_title': 'Avalie',
  'about.vote_desc': 'Vote nos lugares que mais gostou e ajude a comunidade a encontrar os melhores destinos.',

  // Lists page
  'lists.title': 'Listas Curadas',
  'lists.subtitle': 'Descubra coleções especiais de lugares selecionados por nossa comunidade',
  'lists.view_all': 'Ver todos os lugares desta lista',
  'lists.page_title': 'Hidden Gem - Listas',

  // Wander page
  'wander.discover_random': 'Descubra lugares aleatórios em Maputo',

  // Form
  'form.tags_selected_count': '{count}/5 tags selecionadas',
  'form.tag_limit_reached': 'Limite de tags atingido (5)',
  'form.tag_input_placeholder': 'Digite uma tag e pressione Enter, vírgula ou espaço',
  'form.location_hint': 'Clique no mapa para definir a localização ou arraste o marcador',
  'form.opening_hours': 'Horário de Funcionamento',
  'form.opening_hours_note': 'Deixe em branco os dias que não funcionam',
  'form.hour_groups_hint': 'Escolha os dias e defina um horário — adicione outro grupo para dias com horários diferentes',
  'form.add_hour_group': 'Adicionar horário para outros dias',
  'form.remove_hour_group': 'Remover este horário',
  'form.to': 'até',
  'form.price_range': 'Faixa de Preço',
  'form.price_free': 'Grátis',
  'form.price_cheap': 'Barato',
  'form.price_moderate': 'Moderado',
  'form.price_expensive': 'Caro',
  'form.best_time_to_visit': 'Melhor Época para Visitar',
  'form.select_option': 'Selecione uma opção',
  'form.morning': 'Manhã',
  'form.afternoon': 'Tarde',
  'form.evening': 'Noite',
  'form.weekend': 'Final de Semana',
  'form.holidays': 'Feriados',
  'form.other': 'Outro',
  'form.specify_best_time': 'Especifique o melhor horário para visitar',
  'form.accessibility': 'Acessibilidade',
  'form.wheelchair_accessible': 'Acessível para cadeira de rodas',
  'form.family_friendly': 'Adequado para famílias',
  'form.pet_friendly': 'Permite animais de estimação',
  'form.safety_notes': 'Notas de Segurança',
  'form.safety_notes_placeholder': 'Informações importantes sobre segurança ou precauções',
  'form.contact_info': 'Informações de Contato e Redes Sociais',
  'form.website': 'Website',
  'form.phone': 'Telefone',
  'form.email': 'Email',
  'form.instagram': 'Instagram',
  'form.facebook': 'Facebook',
  'form.twitter': 'Twitter/X',
  'form.whatsapp': 'WhatsApp',
  'form.menu_photos': 'Fotos do Menu',
  'form.place_photos': 'Fotos do Lugar',
  'form.place_photos_hint': 'Uma boa foto é a diferença entre um tesouro escondido e um lugar que ninguém clica. Adicione pelo menos uma.',
  'form.photos_required': 'Pelo menos uma foto é obrigatória',
  'form.submit_anonymously': 'Enviar anonimamente',
  'form.section_basics': 'O essencial',
  'form.section_photos': 'Mostre o lugar',
  'form.section_location': 'Onde fica?',
  'form.section_details': 'Bom saber',
  'form.section_contact': 'Como encontrar',
  'form.section_finish': 'Últimos retoques',

  // Image upload
  'upload.add_photos': 'Adicionar Fotos',
  'upload.uploading': 'Enviando...',
  'upload.remove': 'Remover imagem',
  'upload.error_type': 'Tipo de arquivo não suportado. Use apenas JPEG, PNG ou WebP.',
  'upload.error_size': 'Arquivo muito grande. O tamanho máximo é 5MB.',
  'upload.error_max': 'Você pode adicionar no máximo {max} imagens.',
  'upload.error_generic': 'Erro ao fazer upload das imagens. Tente novamente.',

  // Common
  'common.send_message': 'Enviar Mensagem',
  'common.loading_map': 'Carregando mapa...',
  'common.location_error': 'Erro ao obter localização.',
  'common.location_permission_denied': 'Permissão de localização negada.',
  'common.location_unavailable': 'Localização indisponível.',
  'common.location_timeout': 'Tempo limite para obter localização.',
  'common.geolocation_not_supported': 'Geolocalização não é suportada pelo seu navegador.',
  'common.no_image': 'Sem imagem',
  'common.email_placeholder': 'Seu endereço de e-mail',
  'common.share': 'Partilhar',
  'common.report': 'Denunciar',
  'common.url_copied': 'Link copiado para a área de transferência.',

  // Gem detail page
  'gem_detail.not_available': 'Este lugar não está disponível.',
  'gem_detail.added_on': 'Adicionado em',
  'gem_detail.submitted_anonymously': 'Enviado anonimamente',
  'gem_detail.practical_info': 'Informações Práticas',
  'gem_detail.address': 'Endereço',
  'gem_detail.related_gems': 'Lugares Relacionados',
  'gem_detail.edit': 'Editar',
  'gem_detail.menu': 'Menu',
  'gem_detail.view_larger': 'Ver em tamanho maior',

  // Edit gem page
  'edit_gem.title': 'Editar Lugar',

  // Privacy page
  'privacy.title': 'Política de Privacidade',
  'privacy.p1': 'A Hidden Gem Maputo recolhe apenas a informação necessária para publicar os lugares que a comunidade partilha: título, descrição, localização e, quando enviadas, imagens. As submissões podem ser feitas de forma anónima.',
  'privacy.p2': 'Não vendemos nem partilhamos os teus dados com terceiros para fins publicitários. Comentários e votos são guardados associados a um identificador anónimo gerado no teu navegador, não à tua identidade.',
  'privacy.p3': 'Se quiseres que um lugar ou comentário que submeteste seja removido, contacta-nos através da página de Contacto.',

  // Terms page
  'terms.title': 'Termos de Utilização',
  'terms.p1': 'Ao submeter um lugar, confirmas que a informação partilhada é verdadeira e que tens o direito de a publicar. Não aceitamos conteúdo ofensivo, ilegal ou que ponha em causa a segurança de pessoas ou locais.',
  'terms.p2': 'A equipa da Hidden Gem Maputo pode rever, editar ou remover qualquer submissão que viole estes termos ou as diretrizes da comunidade.',
  'terms.p3': 'O serviço é fornecido "tal como está", sem garantias. Usa o bom senso ao visitar lugares partilhados pela comunidade.',

  // Contact page
  'contact.title': 'Contacto',
  'contact.intro': 'Tens uma pergunta, uma sugestão, ou queres reportar um problema com um lugar? Escreve-nos.',
  'contact.email_label': 'Email',

  // Voting
  'voting.title': 'Avalie este lugar',
  'voting.useful': 'Útil',
  'voting.not_useful': 'Não Útil',
  'voting.percentage_suffix': 'dos visitantes acharam este lugar útil',

  // Comments
  'comments.title': 'Comentários',
  'comments.placeholder': 'Deixe seu comentário...',
  'comments.submit': 'Comentar',
  'comments.submitting': 'Enviando...',
  'comments.empty': 'Seja o primeiro a comentar!',
  'comments.error': 'Não foi possível enviar o comentário. Tente novamente.',
  'comments.login_required': 'Entre na sua conta para comentar.',

  // Save button
  'save.saved': 'Salvo',
  'save.save': 'Salvar',

  // Wander page
  'wander.title': 'Modo Wander',
  'wander.save': 'Salvar',
  'wander.next_place': 'Próximo Lugar',
  'wander.save_alert': 'Lugar salvo aos favoritos!',
  'wander.none_found': 'Nenhum lugar encontrado para explorar.',
  'wander.progress': 'de {total} lugares explorados',

  // Tags page
  'tags.title_prefix': 'Lugares com tag:',
  'tags.count_suffix': 'lugares encontrados',
  'tags.empty_title': 'Nenhum lugar encontrado',
  'tags.empty_desc': 'Não encontramos lugares com esta tag.',

  // Categories page descriptions
  'category.restaurant_desc': 'Restaurantes, cafés e experiências culinárias',
  'category.nature_desc': 'Parques, trilhas e espaços ao ar livre',
  'category.art_desc': 'Galerias, murais e expressões culturais',
  'category.view_desc': 'Mirantes e pontos panorâmicos',
  'category.peculiar_desc': 'Lugares únicos e incomuns',

  // Location picker
  'location.use_current': 'Usar minha localização atual',
  'location.search_hint': 'Não encontrou o local? Clique diretamente no mapa para marcar o ponto.',
  'location.no_results': 'Nenhum resultado. Este local pode não estar mapeado ainda — clique no mapa para marcá-lo.',

  // Map
  'map.unavailable': 'Mapa Indisponível',

  // About page
  'about.title': 'Sobre o Hidden Gem',
  'about.subtitle': 'Conheça nossa missão de conectar pessoas com os lugares mais autênticos de Maputo',
  'about.mission_title': 'Nossa Missão',
  'about.mission_p1': 'O Hidden Gem nasceu da paixão por descobrir lugares únicos e autênticos que muitas vezes passam despercebidos pelos guias turísticos tradicionais. Acreditamos que a verdadeira essência de uma cidade está nos lugares que os locais amam e frequentam.',
  'about.mission_p2': 'Nosso objetivo é criar uma comunidade onde moradores e visitantes possam compartilhar e descobrir esses lugares especiais, promovendo uma experiência mais autêntica e significativa da cidade de Maputo.',
  'about.values_title': 'Nossos Valores',
  'about.value_authenticity_title': 'Autenticidade',
  'about.value_authenticity_desc': 'Valorizamos experiências genuínas e locais que representam a verdadeira cultura de Maputo.',
  'about.value_community_title': 'Comunidade',
  'about.value_community_desc': 'Acreditamos no poder da comunidade para compartilhar conhecimento e experiências.',
  'about.value_sustainability_title': 'Sustentabilidade',
  'about.value_sustainability_desc': 'Promovemos o turismo responsável que respeita o meio ambiente e as comunidades locais.',
  'about.contact_title': 'Entre em Contato',
  'about.contact_desc': 'Tem alguma sugestão, dúvida ou quer contribuir com nosso projeto? Adoraríamos ouvir de você!',

  // Admin
  'admin.title': 'Painel de Admin',
  'admin.access_denied_title': 'Acesso restrito',
  'admin.access_denied_desc': 'Esta página é apenas para administradores.',
  'admin.tab_dashboard': 'Resumo',
  'admin.tab_gems': 'Lugares',
  'admin.tab_comments': 'Comentários',
  'admin.tab_reports': 'Denúncias',
  'admin.tab_lists': 'Listas',
  'admin.tab_users': 'Utilizadores',
  'admin.report_filter_open': 'Abertas',
  'admin.report_filter_resolved': 'Resolvidas',
  'admin.report_filter_dismissed': 'Ignoradas',
  'admin.report_filter_all': 'Todas',
  'admin.no_reports_found': 'Nenhuma denúncia encontrada.',
  'admin.resolve': 'Resolver',
  'admin.dismiss': 'Ignorar',
  'admin.lists_new': 'Nova lista',
  'admin.lists_title_label': 'Título',
  'admin.lists_description_label': 'Descrição',
  'admin.lists_cover_label': 'Imagem de capa',
  'admin.lists_save': 'Guardar',
  'admin.lists_cancel': 'Cancelar',
  'admin.lists_edit': 'Editar',
  'admin.lists_delete': 'Eliminar',
  'admin.lists_confirm_delete': 'Eliminar esta lista permanentemente?',
  'admin.lists_published': 'Publicada',
  'admin.lists_unpublished': 'Não publicada',
  'admin.lists_publish': 'Publicar',
  'admin.lists_unpublish': 'Despublicar',
  'admin.lists_manage_gems': 'Gerir lugares',
  'admin.lists_add_gem': 'Adicionar lugar',
  'admin.lists_search_gems_placeholder': 'Procurar lugar pelo título...',
  'admin.lists_no_items': 'Ainda não há lugares nesta lista.',
  'admin.lists_remove_item': 'Remover',
  'admin.lists_none': 'Ainda não há listas. Crie a primeira.',
  'admin.stat_total_gems': 'Lugares no total',
  'admin.stat_pending': 'Pendentes',
  'admin.stat_approved': 'Aprovados',
  'admin.stat_rejected': 'Rejeitados',
  'admin.stat_total_users': 'Utilizadores',
  'admin.stat_total_comments': 'Comentários',
  'admin.stat_total_votes': 'Votos',
  'admin.recent_pending': 'Pendentes recentes',
  'admin.recent_users': 'Novos utilizadores',
  'admin.nothing_pending': 'Nada por rever.',
  'admin.gems_filter_pending': 'Pendentes',
  'admin.gems_filter_approved': 'Aprovados',
  'admin.gems_filter_rejected': 'Rejeitados',
  'admin.gems_filter_all': 'Todos',
  'admin.approve': 'Aprovar',
  'admin.reject': 'Rejeitar',
  'admin.delete': 'Eliminar',
  'admin.reject_reason_placeholder': 'Motivo da rejeição (opcional)',
  'admin.confirm_delete_gem': 'Eliminar este lugar permanentemente? Esta ação não pode ser desfeita.',
  'admin.no_gems_found': 'Nenhum lugar encontrado.',
  'admin.submitted_by': 'Submetido por',
  'admin.unknown_user': 'Utilizador desconhecido',
  'admin.no_comments_found': 'Nenhum comentário encontrado.',
  'admin.comment_on': 'em',
  'admin.confirm_delete_comment': 'Eliminar este comentário permanentemente?',
  'admin.users_email': 'Email',
  'admin.users_name': 'Nome',
  'admin.users_joined': 'Desde',
  'admin.users_gems': 'Lugares',
  'admin.users_role': 'Função',
  'admin.users_status': 'Estado',
  'admin.make_admin': 'Tornar admin',
  'admin.remove_admin': 'Remover admin',
  'admin.ban': 'Desativar',
  'admin.unban': 'Reativar',
  'admin.you': 'Você',
  'admin.status_active': 'Ativo',
  'admin.status_banned': 'Desativado',
  'admin.no_users_found': 'Nenhum utilizador encontrado.',
  'admin.users_search_placeholder': 'Procurar por nome ou email...',
  'admin.gems_search_placeholder': 'Procurar por título...',
  'admin.select_all': 'Selecionar tudo',
  'admin.selected_count': '{count} selecionados',
  'admin.bulk_approve': 'Aprovar selecionados',
  'admin.bulk_reject': 'Rejeitar selecionados',
  'admin.bulk_delete': 'Eliminar selecionados',
  'admin.bulk_confirm_delete': 'Eliminar {count} lugares permanentemente? Esta ação não pode ser desfeita.',
  'admin.stat_open_reports': 'Denúncias abertas',
  'admin.recent_open_reports': 'Denúncias recentes',
  'admin.nothing_reported': 'Nada denunciado.',
  'admin.pager_prev': 'Anterior',
  'admin.pager_next': 'Seguinte',
  'admin.pager_page': 'Página {page} de {total}',
  'admin.tab_activity': 'Atividade',
  'admin.no_activity_found': 'Ainda não há atividade registada.',
  'admin.activity_view_gem': 'ver lugar',
  'admin.action_gem_approved': 'aprovou o lugar',
  'admin.action_gem_rejected': 'rejeitou o lugar',
  'admin.action_gem_pending': 'marcou como pendente o lugar',
  'admin.action_gem_delete': 'eliminou o lugar',
  'admin.action_user_make_admin': 'tornou admin o utilizador',
  'admin.action_user_remove_admin': 'removeu o acesso de admin do utilizador',
  'admin.action_user_ban': 'desativou o utilizador',
  'admin.action_user_unban': 'reativou o utilizador',
  'admin.action_report_resolve': 'resolveu uma denúncia sobre',
  'admin.action_report_dismiss': 'ignorou uma denúncia sobre',

  // Profile
  'profile.title': 'O Meu Perfil',
  'profile.login_required_title': 'Sessão necessária',
  'profile.login_required_desc': 'Entre na sua conta para ver o seu perfil.',
  'profile.tab_details': 'Perfil',
  'profile.tab_password': 'Password',
  'profile.tab_mygems': 'Os Meus Lugares',
  'profile.tab_saved': 'Guardados',
  'profile.change_avatar': 'Alterar foto',
  'profile.avatar_hint': 'JPG, PNG ou WEBP, até 5MB',
  'profile.avatar_error': 'Erro ao enviar a foto. Tente novamente.',
  'profile.saved': 'Alterações guardadas.',
  'profile.saving': 'A guardar...',
  'profile.save_changes': 'Guardar alterações',
  'profile.current_password': 'Password atual',
  'profile.password_changed': 'Password alterada com sucesso.',
  'profile.change_password_button': 'Alterar password',
  'profile.no_gems': 'Ainda não submeteu nenhum lugar.',
  'profile.pending_note': 'Em análise pela nossa equipa.',
  'profile.no_saved': 'Ainda não guardou nenhum lugar.',

  // Visitor Photos
  'photos.title': 'Fotos de Visitantes',
  'photos.login_required': 'Entre na sua conta para partilhar uma foto.',
  'photos.add': 'Adicionar uma foto',
  'photos.caption_placeholder': 'Uma legenda (opcional)...',
  'photos.post': 'Publicar',
  'photos.posting': 'A publicar...',
  'photos.upload_error': 'Erro ao publicar a foto. Tente novamente.',
  'photos.confirm_delete': 'Remover esta foto permanentemente?',
  'photos.empty': 'Ainda não há fotos de visitantes. Seja o primeiro!',
  'photos.feed_title': 'Fotos da Comunidade',
  'photos.feed_subtitle': 'Todas as fotos partilhadas por quem visitou os lugares desta comunidade',
  'photos.feed_empty': 'Ainda não há fotos partilhadas.',
  'photos.load_more': 'Ver mais fotos',
  'photos.loading_more': 'A carregar...',

  // Search
  'search.placeholder': 'Procurar lugares...',
  'search.submit': 'Procurar',
  'search.title': 'Pesquisa',
  'search.results_for': 'Resultados para',
  'search.no_results': 'Nenhum lugar encontrado para essa pesquisa.',
  'search.searching': 'A procurar...',
  'search.no_suggestions': 'Nenhuma sugestão encontrada.',
  'search.see_all': 'Ver todos os resultados para "{query}"',

  // Report flow
  'report.title': 'Denunciar este lugar',
  'report.login_required': 'É preciso entrar na sua conta para denunciar um lugar.',
  'report.reason_label': 'Motivo',
  'report.reason_spam': 'Spam ou publicidade',
  'report.reason_inappropriate': 'Conteúdo impróprio ou ofensivo',
  'report.reason_incorrect_info': 'Informação incorreta',
  'report.reason_closed': 'Este lugar já não existe/fechou',
  'report.reason_other': 'Outro motivo',
  'report.details_label': 'Detalhes adicionais (opcional)',
  'report.details_placeholder': 'Descreva o problema...',
  'report.submit': 'Enviar denúncia',
  'report.submitting': 'A enviar...',
  'report.success': 'Denúncia enviada. Obrigado por ajudar a manter o site de qualidade.',
  'report.error': 'Não foi possível enviar a denúncia. Tente novamente.',
  'report.cancel': 'Cancelar',

  // Curated lists
  'lists.empty': 'Ainda não há listas publicadas.',
  'lists.gem_count': '{count} lugares',
  'lists.back_to_lists': 'Voltar às listas',
  'lists.not_available': 'Esta lista não está disponível.',
  'lists.list_empty': 'Ainda não há lugares nesta lista.',
};

// English translations
const enTranslations = {
  // Navigation
  'nav.explore': 'Explore',
  'nav.add': 'Add',
  'nav.about': 'About',
  'nav.login': 'Login',
  'nav.logout': 'Logout',
  'nav.admin': 'Admin',
  'nav.profile': 'Profile',
  'nav.photos': 'Photos',

  // Auth
  'auth.login_title': 'Log In',
  'auth.login_subtitle': 'Log in to your account to add and manage your places.',
  'auth.register_title': 'Create Account',
  'auth.register_subtitle': 'Create an account to start sharing your secret places.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.display_name': 'Name',
  'auth.password_hint': 'At least 8 characters',
  'auth.login_button': 'Log In',
  'auth.register_button': 'Create Account',
  'auth.logging_in': 'Logging in...',
  'auth.creating_account': 'Creating account...',
  'auth.no_account': "Don't have an account?",
  'auth.have_account': 'Already have an account?',
  'auth.create_one': 'Create one',
  'auth.login_here': 'Log in',
  'auth.posting_as': 'Posting as',
  'auth.generic_error': 'Something went wrong. Please try again.',
  'auth.passwords_dont_match': "Passwords don't match.",

  // Auth - forgot/reset password
  'auth.forgot_password': 'Forgot password?',
  'auth.forgot_title': 'Reset Password',
  'auth.forgot_subtitle': "Enter your email and we'll send you a link to reset your password.",
  'auth.forgot_button': 'Send reset link',
  'auth.forgot_sending': 'Sending...',
  'auth.forgot_check_email_title': 'Check your email',
  'auth.forgot_check_email_desc': "If an account exists with this email, we've sent a link to reset your password.",
  'auth.forgot_dev_title': 'Temporary password generated',
  'auth.forgot_dev_desc': "No email service is configured yet, so here's a temporary password you can log in with:",
  'auth.forgot_dev_copy': 'Copy',
  'auth.forgot_dev_copied': 'Copied!',
  'auth.forgot_dev_note': "This only shows up because email isn't configured yet (dev mode). We recommend changing your password after logging in.",
  'auth.back_to_login': 'Back to login',
  'auth.reset_title': 'New Password',
  'auth.reset_subtitle': 'Choose a new password for your account.',
  'auth.reset_new_password': 'New password',
  'auth.reset_confirm_password': 'Confirm password',
  'auth.reset_button': 'Reset password',
  'auth.reset_saving': 'Saving...',
  'auth.reset_invalid_title': 'Invalid link',
  'auth.reset_invalid_desc': 'This reset link is missing or invalid. Please request a new one.',
  'auth.reset_success_title': 'Password reset',
  'auth.reset_success_desc': 'Your password has been changed successfully. You can log in now.',

  // Auth - email verification
  'auth.verify_checking': 'Confirming your email...',
  'auth.verify_success_title': 'Email confirmed!',
  'auth.verify_success_desc': 'Your email has been confirmed successfully.',
  'auth.verify_go_home': 'Go to homepage',
  'auth.verify_invalid_title': "Couldn't confirm",
  'auth.verify_invalid_desc': 'This confirmation link is missing, expired, or already used.',
  'auth.verify_banner_text': 'Confirm your email to make sure you keep access to your account.',
  'auth.verify_banner_resend': 'Resend email',
  'auth.verify_banner_sending': 'Sending...',
  'auth.verify_banner_sent': 'Confirmation email sent — check your inbox.',

  // Common
  'common.loading': 'Loading...',
  'common.submit': 'Submit',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.clear_all': 'Clear all',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.previous': 'Previous',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.sort': 'Sort',

  // Categories
  'category.restaurant': 'Restaurant/Café',
  'category.bar': 'Bar/Drinks',
  'category.nature': 'Nature',
  'category.art': 'Art',
  'category.view': 'View',
  'category.peculiar': 'Peculiar',
  'category.all': 'All',

  // Form
  'form.title': 'Title',
  'form.description': 'Description',
  'form.category': 'Category',
  'form.tags': 'Tags',
  'form.location': 'Location',
  'form.images': 'Images',
  'form.submit': 'Submit Place',
  'form.submitting': 'Submitting...',
  'form.required': 'required',

  // Placeholders
  'placeholder.title': 'Place name',
  'placeholder.description': 'Describe this place and what makes it special...',
  'placeholder.select_category': 'Select a category',
  'placeholder.search_location': 'Search location...',

  // Messages
  'message.submit_success': 'Your place has been submitted successfully and will be reviewed by our team soon.',
  'message.submit_success_approval': 'After approval, your place will appear on the map and can be discovered by other users.',
  'message.submit_another': 'Add Another Place',
  'message.explore_more': 'Explore More Places',
  'message.no_places': 'No places found',
  'message.no_places_suggestion': 'Try changing the filters or be the first to add a place!',
  'message.add_first_place': 'Add Place',

  // Footer
  'footer.description': 'Discover Maputo\'s hidden gems shared by locals.',
  'footer.explore': 'Explore',
  'footer.community': 'Community',
  'footer.legal': 'Legal',
  'footer.copyright': '© {year} Hidden Gem. All rights reserved.',
  'footer.lists': 'Lists',
  'footer.categories': 'Categories',
  'footer.guidelines': 'Guidelines',
  'footer.contact': 'Contact',
  'footer.privacy': 'Privacy',
  'footer.terms': 'Terms',

  // Submit page
  'submit.title': 'Share a Hidden Gem',
  'submit.subtitle': 'Help others discover Maputo\'s special places. All places are reviewed before being published.',
  'submit.guidelines_title': 'Community Guidelines',
  'submit.login_required_title': 'Log in to add a place',
  'submit.login_required_desc': 'You need an account to share your secret places with the community.',
  'submit.login_required_button': 'Log In',
  'submit.login_required_register': "Don't have an account?",
  'submit.guideline_1': 'Share places that are not widely known or touristy',
  'submit.guideline_2': 'Provide accurate and detailed information about the place',
  'submit.guideline_3': 'Respect the privacy and security of shared places',
  'submit.guideline_4': 'Do not share places that may cause environmental damage or disturb local communities',
  'submit.map_title': 'Location on Map',

  // Maputo page
  'maputo.title': 'Maputo',
  'maputo.secret_places': 'secret places',
  'maputo.loading_places': 'Loading places...',
  'maputo.all': 'All',
  'maputo.popular': 'Popular',
  'maputo.newest': 'Newest',
  'maputo.top_rated': 'Top Rated',
  'maputo.closest': 'Closest',
  'maputo.view_grid': 'Grid',
  'maputo.view_map': 'Map',

  // Hero
  'hero.title': 'Discover Maputo\'s secret places shared by locals.',
  'hero.subtitle': 'Find hidden cafes, local views, unmarked trails, and much more.',
  'hero.explore_button': 'Explore Maputo.',
  'hero.share_button': 'Share a Place.',
  'hero.wander_button': 'Wander Mode',

  // Index page
  'index.featured_title': 'Featured Places',
  'index.featured_subtitle': 'Discover some of the most special places shared by our community',
  'index.featured_empty': "No approved places yet. Be the first to share one!",
  'index.view_all_maputo': 'View all places in Maputo',
  'index.categories_title': 'Explore by Category',
  'index.categories_subtitle': 'Find special places organized by type of experience',
  'index.how_it_works_title': 'How It Works',
  'index.how_it_works_subtitle': 'Join our community and start discovering Maputo\'s most authentic places',
  'index.discover_title': 'Discover',
  'index.discover_desc': 'Explore unique places on the map or browse categories to find something special',
  'index.share_title': 'Share',
  'index.share_desc': 'Add your own secret places and help others discover the city',
  'index.vote_title': 'Vote',
  'index.vote_desc': 'Rate places to help the community find the best locations',
  'index.lists_title': 'Popular Lists',
  'index.lists_subtitle': 'Discover special collections of places selected by our community',
  'index.cafes_list_title': 'Hidden Cafes of Maputo',
  'index.cafes_list_desc': 'The best cafes that only locals know',
  'index.views_list_title': 'Amazing Views of Maputo',
  'index.views_list_desc': 'The best viewpoints and city overlooks',
  'index.view_all_lists': 'View all lists',
  'index.recent_photos_title': 'Photos From People Who Went',
  'index.recent_photos_subtitle': 'Moments shared by people who visited these places',
  'index.view_all_photos': 'View all photos',
  'index.newsletter_title': 'Receive New Places',
  'index.newsletter_subtitle': 'Subscribe to our newsletter to receive the latest places added to our community',
  'index.subscribe_button': 'Subscribe',

  // Categories page
  'categories.title': 'Explore by Categories',
  'categories.subtitle': 'Find special places organized by type of experience',

  // About page
  'about.how_it_works_title': 'How It Works',
  'about.discover_title': 'Discover',
  'about.discover_desc': 'Explore our interactive map and find unique places in Maputo, from hidden cafes to amazing trails.',
  'about.share_title': 'Share',
  'about.share_desc': 'Add your own favorite places and help others discover the city like a local.',
  'about.vote_title': 'Rate',
  'about.vote_desc': 'Vote on places you liked and help the community find the best destinations.',

  // Lists page
  'lists.title': 'Curated Lists',
  'lists.subtitle': 'Discover special collections of places selected by our community',
  'lists.view_all': 'View all places in this list',
  'lists.page_title': 'Hidden Gem - Lists',

  // Wander page
  'wander.discover_random': 'Discover random places in Maputo',

  // Form
  'form.tags_selected_count': '{count}/5 tags selected',
  'form.tag_limit_reached': 'Tag limit reached (5)',
  'form.tag_input_placeholder': 'Type a tag and press Enter, comma or space',
  'form.location_hint': 'Click on the map to set the location or drag the marker',
  'form.opening_hours': 'Opening Hours',
  'form.opening_hours_note': 'Leave blank for days that are closed',
  'form.hour_groups_hint': 'Pick the days and set a time — add another group for days with different hours',
  'form.add_hour_group': 'Add hours for other days',
  'form.remove_hour_group': 'Remove these hours',
  'form.to': 'to',
  'form.price_range': 'Price Range',
  'form.price_free': 'Free',
  'form.price_cheap': 'Cheap',
  'form.price_moderate': 'Moderate',
  'form.price_expensive': 'Expensive',
  'form.best_time_to_visit': 'Best Time to Visit',
  'form.select_option': 'Select an option',
  'form.morning': 'Morning',
  'form.afternoon': 'Afternoon',
  'form.evening': 'Evening',
  'form.weekend': 'Weekend',
  'form.holidays': 'Holidays',
  'form.other': 'Other',
  'form.specify_best_time': 'Specify the best time to visit',
  'form.accessibility': 'Accessibility',
  'form.wheelchair_accessible': 'Wheelchair accessible',
  'form.family_friendly': 'Family friendly',
  'form.pet_friendly': 'Pet friendly',
  'form.safety_notes': 'Safety Notes',
  'form.safety_notes_placeholder': 'Important information about safety or precautions',
  'form.contact_info': 'Contact Information and Social Media',
  'form.website': 'Website',
  'form.phone': 'Phone',
  'form.email': 'Email',
  'form.instagram': 'Instagram',
  'form.facebook': 'Facebook',
  'form.twitter': 'Twitter/X',
  'form.whatsapp': 'WhatsApp',
  'form.menu_photos': 'Menu Photos',
  'form.place_photos': 'Place Photos',
  'form.place_photos_hint': "A good photo is the difference between a hidden gem and a place nobody clicks on. Add at least one.",
  'form.photos_required': 'At least one photo is required',
  'form.submit_anonymously': 'Submit anonymously',
  'form.section_basics': 'The basics',
  'form.section_photos': 'Show it off',
  'form.section_location': 'Where is it?',
  'form.section_details': 'Good to know',
  'form.section_contact': 'How to find them',
  'form.section_finish': 'Finishing touches',

  // Image upload
  'upload.add_photos': 'Add Photos',
  'upload.uploading': 'Uploading...',
  'upload.remove': 'Remove image',
  'upload.error_type': 'Unsupported file type. Use JPEG, PNG, or WebP only.',
  'upload.error_size': 'File too large. Maximum size is 5MB.',
  'upload.error_max': 'You can add a maximum of {max} images.',
  'upload.error_generic': 'Error uploading images. Please try again.',

  // Common
  'common.send_message': 'Send Message',
  'common.loading_map': 'Loading map...',
  'common.location_error': 'Error getting location.',
  'common.location_permission_denied': 'Location permission denied.',
  'common.location_unavailable': 'Location unavailable.',
  'common.location_timeout': 'Location timeout.',
  'common.geolocation_not_supported': 'Geolocation is not supported by your browser.',
  'common.no_image': 'No image',
  'common.email_placeholder': 'Your email address',
  'common.share': 'Share',
  'common.report': 'Report',
  'common.url_copied': 'Link copied to clipboard.',

  // Gem detail page
  'gem_detail.not_available': 'This place is not available.',
  'gem_detail.added_on': 'Added on',
  'gem_detail.submitted_anonymously': 'Submitted anonymously',
  'gem_detail.practical_info': 'Practical Info',
  'gem_detail.address': 'Address',
  'gem_detail.related_gems': 'Related Places',
  'gem_detail.edit': 'Edit',
  'gem_detail.menu': 'Menu',
  'gem_detail.view_larger': 'View larger',

  // Edit gem page
  'edit_gem.title': 'Edit Place',

  // Privacy page
  'privacy.title': 'Privacy Policy',
  'privacy.p1': 'Hidden Gem Maputo only collects what is needed to publish the places the community shares: title, description, location and, when provided, photos. Submissions can be made anonymously.',
  'privacy.p2': "We don't sell or share your data with third parties for advertising. Comments and votes are stored against an anonymous identifier generated in your browser, not your identity.",
  'privacy.p3': 'If you would like a place or comment you submitted removed, reach out via the Contact page.',

  // Terms page
  'terms.title': 'Terms of Use',
  'terms.p1': 'By submitting a place, you confirm the information is accurate and that you have the right to share it. We do not accept offensive or illegal content, or anything that puts people or locations at risk.',
  'terms.p2': 'The Hidden Gem Maputo team may review, edit or remove any submission that violates these terms or the community guidelines.',
  'terms.p3': 'The service is provided "as is", without warranties. Use good judgment when visiting places shared by the community.',

  // Contact page
  'contact.title': 'Contact',
  'contact.intro': 'Have a question, a suggestion, or need to report a problem with a place? Reach out.',
  'contact.email_label': 'Email',

  // Voting
  'voting.title': 'Rate this place',
  'voting.useful': 'Helpful',
  'voting.not_useful': 'Not helpful',
  'voting.percentage_suffix': 'of visitors found this place helpful',

  // Comments
  'comments.title': 'Comments',
  'comments.placeholder': 'Leave a comment...',
  'comments.submit': 'Comment',
  'comments.submitting': 'Sending...',
  'comments.empty': 'Be the first to comment!',
  'comments.error': "Couldn't post your comment. Please try again.",
  'comments.login_required': 'Log in to leave a comment.',

  // Save button
  'save.saved': 'Saved',
  'save.save': 'Save',

  // Wander page
  'wander.title': 'Wander Mode',
  'wander.save': 'Save',
  'wander.next_place': 'Next Place',
  'wander.save_alert': 'Place saved to favorites!',
  'wander.none_found': 'No places found to explore.',
  'wander.progress': 'of {total} places explored',

  // Tags page
  'tags.title_prefix': 'Places tagged:',
  'tags.count_suffix': 'places found',
  'tags.empty_title': 'No places found',
  'tags.empty_desc': "We couldn't find any places with this tag.",

  // Categories page descriptions
  'category.restaurant_desc': 'Restaurants, cafes and culinary experiences',
  'category.nature_desc': 'Parks, trails and outdoor spaces',
  'category.art_desc': 'Galleries, murals and cultural expression',
  'category.view_desc': 'Viewpoints and scenic spots',
  'category.peculiar_desc': 'Unique and unusual places',

  // Location picker
  'location.use_current': 'Use my current location',
  'location.search_hint': "Can't find the place? Click directly on the map to pin it.",
  'location.no_results': "No results. This place might not be mapped yet — click on the map to pin it.",

  // Map
  'map.unavailable': 'Map unavailable',

  // About page
  'about.title': 'About Hidden Gem',
  'about.subtitle': "Learn about our mission to connect people with Maputo's most authentic places",
  'about.mission_title': 'Our Mission',
  'about.mission_p1': "Hidden Gem was born from a passion for discovering unique, authentic places that often go unnoticed by traditional tourist guides. We believe a city's true essence lives in the places locals love and frequent.",
  'about.mission_p2': 'Our goal is to build a community where residents and visitors can share and discover these special places, creating a more authentic and meaningful experience of Maputo.',
  'about.values_title': 'Our Values',
  'about.value_authenticity_title': 'Authenticity',
  'about.value_authenticity_desc': "We value genuine, local experiences that represent Maputo's true culture.",
  'about.value_community_title': 'Community',
  'about.value_community_desc': 'We believe in the power of community to share knowledge and experiences.',
  'about.value_sustainability_title': 'Sustainability',
  'about.value_sustainability_desc': 'We promote responsible tourism that respects the environment and local communities.',
  'about.contact_title': 'Get in Touch',
  'about.contact_desc': "Have a suggestion, a question, or want to contribute to our project? We'd love to hear from you!",

  // Admin
  'admin.title': 'Admin Panel',
  'admin.access_denied_title': 'Restricted access',
  'admin.access_denied_desc': 'This page is for administrators only.',
  'admin.tab_dashboard': 'Overview',
  'admin.tab_gems': 'Places',
  'admin.tab_comments': 'Comments',
  'admin.tab_reports': 'Reports',
  'admin.tab_lists': 'Lists',
  'admin.tab_users': 'Users',
  'admin.report_filter_open': 'Open',
  'admin.report_filter_resolved': 'Resolved',
  'admin.report_filter_dismissed': 'Dismissed',
  'admin.report_filter_all': 'All',
  'admin.no_reports_found': 'No reports found.',
  'admin.resolve': 'Resolve',
  'admin.dismiss': 'Dismiss',
  'admin.lists_new': 'New list',
  'admin.lists_title_label': 'Title',
  'admin.lists_description_label': 'Description',
  'admin.lists_cover_label': 'Cover image',
  'admin.lists_save': 'Save',
  'admin.lists_cancel': 'Cancel',
  'admin.lists_edit': 'Edit',
  'admin.lists_delete': 'Delete',
  'admin.lists_confirm_delete': 'Permanently delete this list?',
  'admin.lists_published': 'Published',
  'admin.lists_unpublished': 'Unpublished',
  'admin.lists_publish': 'Publish',
  'admin.lists_unpublish': 'Unpublish',
  'admin.lists_manage_gems': 'Manage places',
  'admin.lists_add_gem': 'Add place',
  'admin.lists_search_gems_placeholder': 'Search a place by title...',
  'admin.lists_no_items': 'No places in this list yet.',
  'admin.lists_remove_item': 'Remove',
  'admin.lists_none': 'No lists yet. Create the first one.',
  'admin.stat_total_gems': 'Total places',
  'admin.stat_pending': 'Pending',
  'admin.stat_approved': 'Approved',
  'admin.stat_rejected': 'Rejected',
  'admin.stat_total_users': 'Users',
  'admin.stat_total_comments': 'Comments',
  'admin.stat_total_votes': 'Votes',
  'admin.recent_pending': 'Recently pending',
  'admin.recent_users': 'New users',
  'admin.nothing_pending': 'Nothing to review.',
  'admin.gems_filter_pending': 'Pending',
  'admin.gems_filter_approved': 'Approved',
  'admin.gems_filter_rejected': 'Rejected',
  'admin.gems_filter_all': 'All',
  'admin.approve': 'Approve',
  'admin.reject': 'Reject',
  'admin.delete': 'Delete',
  'admin.reject_reason_placeholder': 'Reason for rejecting (optional)',
  'admin.confirm_delete_gem': 'Permanently delete this place? This cannot be undone.',
  'admin.no_gems_found': 'No places found.',
  'admin.submitted_by': 'Submitted by',
  'admin.unknown_user': 'Unknown user',
  'admin.no_comments_found': 'No comments found.',
  'admin.comment_on': 'on',
  'admin.confirm_delete_comment': 'Permanently delete this comment?',
  'admin.users_email': 'Email',
  'admin.users_name': 'Name',
  'admin.users_joined': 'Joined',
  'admin.users_gems': 'Places',
  'admin.users_role': 'Role',
  'admin.users_status': 'Status',
  'admin.make_admin': 'Make admin',
  'admin.remove_admin': 'Remove admin',
  'admin.ban': 'Disable',
  'admin.unban': 'Re-enable',
  'admin.you': 'You',
  'admin.status_active': 'Active',
  'admin.status_banned': 'Disabled',
  'admin.no_users_found': 'No users found.',
  'admin.users_search_placeholder': 'Search by name or email...',
  'admin.gems_search_placeholder': 'Search by title...',
  'admin.select_all': 'Select all',
  'admin.selected_count': '{count} selected',
  'admin.bulk_approve': 'Approve selected',
  'admin.bulk_reject': 'Reject selected',
  'admin.bulk_delete': 'Delete selected',
  'admin.bulk_confirm_delete': 'Permanently delete {count} places? This cannot be undone.',
  'admin.stat_open_reports': 'Open reports',
  'admin.recent_open_reports': 'Recent reports',
  'admin.nothing_reported': 'Nothing reported.',
  'admin.pager_prev': 'Previous',
  'admin.pager_next': 'Next',
  'admin.pager_page': 'Page {page} of {total}',
  'admin.tab_activity': 'Activity',
  'admin.no_activity_found': 'No activity logged yet.',
  'admin.activity_view_gem': 'view place',
  'admin.action_gem_approved': 'approved the place',
  'admin.action_gem_rejected': 'rejected the place',
  'admin.action_gem_pending': 'marked as pending the place',
  'admin.action_gem_delete': 'deleted the place',
  'admin.action_user_make_admin': 'made admin the user',
  'admin.action_user_remove_admin': "removed admin access from the user",
  'admin.action_user_ban': 'disabled the user',
  'admin.action_user_unban': 're-enabled the user',
  'admin.action_report_resolve': 'resolved a report on',
  'admin.action_report_dismiss': 'dismissed a report on',

  // Profile
  'profile.title': 'My Profile',
  'profile.login_required_title': 'Login required',
  'profile.login_required_desc': 'Log in to your account to view your profile.',
  'profile.tab_details': 'Profile',
  'profile.tab_password': 'Password',
  'profile.tab_mygems': 'My Places',
  'profile.tab_saved': 'Saved',
  'profile.change_avatar': 'Change photo',
  'profile.avatar_hint': 'JPG, PNG or WEBP, up to 5MB',
  'profile.avatar_error': 'Error uploading the photo. Please try again.',
  'profile.saved': 'Changes saved.',
  'profile.saving': 'Saving...',
  'profile.save_changes': 'Save changes',
  'profile.current_password': 'Current password',
  'profile.password_changed': 'Password changed successfully.',
  'profile.change_password_button': 'Change password',
  'profile.no_gems': "You haven't submitted any places yet.",
  'profile.pending_note': 'Under review by our team.',
  'profile.no_saved': "You haven't saved any places yet.",

  // Visitor Photos
  'photos.title': 'Visitor Photos',
  'photos.login_required': 'Log in to share a photo.',
  'photos.add': 'Add a photo',
  'photos.caption_placeholder': 'A caption (optional)...',
  'photos.post': 'Post',
  'photos.posting': 'Posting...',
  'photos.upload_error': 'Error posting the photo. Please try again.',
  'photos.confirm_delete': 'Permanently remove this photo?',
  'photos.empty': 'No visitor photos yet. Be the first!',
  'photos.feed_title': 'Community Photos',
  'photos.feed_subtitle': 'Every photo shared by people who visited these places',
  'photos.feed_empty': 'No photos shared yet.',
  'photos.load_more': 'Load more photos',
  'photos.loading_more': 'Loading...',

  // Search
  'search.placeholder': 'Search places...',
  'search.submit': 'Search',
  'search.title': 'Search',
  'search.results_for': 'Results for',
  'search.no_results': 'No places found for that search.',
  'search.searching': 'Searching...',
  'search.no_suggestions': 'No suggestions found.',
  'search.see_all': 'See all results for "{query}"',

  // Report flow
  'report.title': 'Report this place',
  'report.login_required': 'Log in to report a place.',
  'report.reason_label': 'Reason',
  'report.reason_spam': 'Spam or advertising',
  'report.reason_inappropriate': 'Inappropriate or offensive content',
  'report.reason_incorrect_info': 'Incorrect information',
  'report.reason_closed': 'This place no longer exists/is closed',
  'report.reason_other': 'Other reason',
  'report.details_label': 'Additional details (optional)',
  'report.details_placeholder': 'Describe the issue...',
  'report.submit': 'Send report',
  'report.submitting': 'Sending...',
  'report.success': 'Report sent. Thanks for helping keep the site accurate.',
  'report.error': "Couldn't send the report. Please try again.",
  'report.cancel': 'Cancel',

  // Curated lists
  'lists.empty': 'No lists published yet.',
  'lists.gem_count': '{count} places',
  'lists.back_to_lists': 'Back to lists',
  'lists.not_available': 'This list is not available.',
  'lists.list_empty': 'No places in this list yet.',
};

const translations = {
  pt: ptTranslations,
  en: enTranslations,
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof ptTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
